name = "AeroMDAO"
uuid = "ae1513eb-aba2-415b-9b88-80f66c7c7c76"
authors = ["GodotMisogi <arjitseth@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
